openapi: 3.0.0
x-apiname: persons
x-responsetime: 10000

info:
  title: Persons
  description: 'This an API for managing persons that exist in the Union Fashion persons, allowing any desktop, web, mobile, or device application to integrate with persons made via our platform.'
  version: '1.0'
  contact:
    name: 'Example Support'
    url: https://support.example.com/
    email: admin@admin.com
  license:
    name: BSD-1-Clause
    url: https://opensource.org/license/bsd-1-clause/
  termsOfService: https://example.com/tos

servers:
- url: '{{baseUrl}}'
paths:
  /persons:
    post:
      summary: Add Person
      description: Creates a new person.
      operationId: addPerson
      tags:
        - Persons
      requestBody:
        description: 'A person schema.'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
            example:
              category: Jeans
              brand: Union
              color: black
              gender: m
              unitPrice: 49.99
              unitSalePrice: 29.99
      security:
      - api_key: []
      responses:
        201:
          description: 'Successful creation of person.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
              example:
                status: success
        500:
          description: Internal server error
      deprecated: false
    get:
      summary: Get Persons
      description: Pulls a list of all person
      operationId: getPersons
      tags:
        - Persons
      parameters:
      - name: query
        example: all-users
        in: query
        description: 'A query to search for persons by.'
        required: true
        schema:
          $ref: '#/components/schemas/Persons'
          type: string
          example: 'shirts'
      security:
      - api_key: []
      responses:
        200:
          description: 'Get list of all persons'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Persons'
              example:
                status: success
        403:
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Persons'
              example:
                status: failure
        500:
          description: Internal server error
      deprecated: false
  '/persons/{personId}':
    get:
      summary: Get Person
      description: Retrieves a single person.
      operationId: getPerson
      tags:
      - Persons
      parameters:
        - name: personId
          example: 1234-4321-1234-4321
          in: path
          description: The person ID to retrieve.
          required: true
          schema:
            $ref: '#/components/schemas/Persons'
            type: string
            example: person-one
      responses:
        200:
          description: 'Single person.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
              example:
                status: success
        500:
          description: Internal server error
      deprecated: false
      security:
      - api_key: []
    put:
      summary: Update
      description: Supports either full or partial updates.
      operationId: updatePerson
      tags:
      - Persons
      parameters:
        - name: personId
          example: 1234-4321-1234-4321
          in: path
          description: The person ID to retrieve.
          required: true
          schema:
            $ref: '#/components/schemas/Person'
            type: string
            example: person-one
      security:
      - api_key: []
      requestBody:
        description: 'A person object.'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
            example:
              unitSalePrice: 29.99
        required: true
      responses:
        200:
          description: 'Successfully updated.'
        500:
          description: Internal server error
      deprecated: false
    delete:
      tags:
      - Persons
      summary: Delete
      description: 'Delete an individual person.'
      operationId: deletePerson
      parameters:
        - name: personId
          example: 1234-4321-1234-4321
          in: path
          description: The person ID to retrieve.
          required: true
          schema:
            $ref: '#/components/schemas/Person'
            type: string
            example: person-one
      security:
      - api_key: []
      responses:
        204:
          description: 'Person deleted.'
        500:
          description: Internal server error
      deprecated: false
components:
  securitySchemes:
    api_key:
      type: "apiKey"
      name: "x-api-key"
      in: "header"
  schemas:
    Persons:
      type: object
      items:
        $ref: "#/components/schemas/Person"
    Person:
      title: Person
      required:
      - identifier
      - name
      type: object
      properties:
        identifier:
          type: string
        firstName:
          type: string
        lastName:
          type: string          
        bio:
          type: string
        image:
          type: string
        url:
          type: string
        title:
          type: string
        dateOfBirth:
          type: string          
      example:
        identifier: albert-einstein
        firstName: Albert
        lastName: Einstein
        bio: black
        image: m
        url: 49.99
        title: 29.99
        dateOfBirth: 29.99

tags:
- name: Persons
  description: 'A person object.'

security:
    - api_key : []

