name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/API Tests.json" -e "27254840-65c33cfa-c918-4051-9865-7693fd5fc527" --integration-id "146374-${{ github.run_id }}"
          # Lint your API using Postman CLI
          postman api lint 6c88249a-4ce0-4097-b949-44a534dab5e3 --integration-id 146374
